chain:
  - name: SOLANA
    wsRpc: wss://solana-mainnet.core.chainstack.com/c0260deb07f06fce4403c9a4033adafa
    queryRpc:
      - https://dawn-spring-theorem.solana-mainnet.quiknode.pro/04e4ec0d9800a4f9246ad8c12d2dec501ef5435c
    slotParallel: 1
    txDetal: 200
    rangeRound: 200
  - name: ETH
    wsRpc: wss://mainnet.infura.io/ws/v3/your-infura-project-id
    queryRpc:
      - https://rpc.ankr.com/eth
    slotParallel: 1
    txDetal: 200
    rangeRound: 200
  - name: BSC
    wsRpc: wss://mainnet.infura.io/ws/v3/your-infura-project-id
    queryRpc:
      - https://go.getblock.asia/9f60b50f823647d181e389fd72440ba3
    slotParallel: 1
    txDetal: 200
    rangeRound: 200
  - name: BSC_TESTNET
    wsRpc: 
    queryRpc:
      - https://bsc-testnet.public.blastapi.io
    slotParallel: 1
    txDetal: 200
    rangeRound: 200 

database:
  type: mysql
  host: ssh.langbridge
  port: 
  user: root
  password: 
  dbname: walletus_db_main
  sslmode: disable
  TimeZone: Asia/Shanghai

log:
  path: /Users/jclee/Desktop/chaos

indexerRoot:
  path: /Users/jclee/Desktop/chaos/index

cmd:
  port: 9501
  host: localhost

http:
  port: 18080

allStart: 1
proxyEnable : true

contract:
  nAddress: 0xB82582bf335bc4f57ec3c536E67019e1FA263F81